spring.application.name=TraineeAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/traineeDB
spring.datasource.username=postgres
spring.datasource.password=shubham
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8085
